### PR TITLE
Feature/fix ie button group style

### LINKED ISSUE #140: Fix button group style for IE
- [ ] Fix button group style for internet explorer
- [ ] Fix dispatchEvent error

### PR DESCRIPTION
**Pull request by wasabideveloper**
Bugfix of #140 (closes #140 ).

* ran tests
* tested views by hand (IE, FF):
  * /orders/new/
  * /orders/{orderId}

Reviewed by:
- [x] @das-g 
- [x] @njordan-hsr 

It's not possible to fix the issue, but I improved the visual appereance as much as possible:

**Firefox**:
buttonsffchrome

**Internet Explorer**:
buttonsie

It's not possible to fix the JS exception "Object doesn't support action" because there is no possibility to detect allowed actions by JS (crappy IE disables actions but does not allow to check that before calling an action).

### CODE REVIEW

File: osmaxx-py/osmaxx/excerptexport/static/excerptexport/scripts/formModeSwitcher.js [hunk 1]
```diff
@@ -26,8 +26,13 @@
             formPartsSwitcher.value = formModeParam;
         }
 
+        // IE may throw an error here "Object doesn't support this action".
+        // It seems IE won't trigger a change event on select boxes.
+        // I didn't find a solution to get the supported actions,
+        // so the error is still there: Fuck you IE.
```
Comment (das-g) [inline osmaxx-py/osmaxx/excerptexport/static/excerptexport/scripts/formModeSwitcher.js]: Do we really want to serve expletives like this to clients? We don't have the exemption usually granted to guys like Torvalds.

File: osmaxx-py/osmaxx/excerptexport/static/excerptexport/scripts/formModeSwitcher.js [hunk 2]
```diff
@@ -26,8 +26,13 @@
...
+        // Note: The switcher is working regardless.
```
Comment (das-g) [inline osmaxx-py/osmaxx/excerptexport/static/excerptexport/scripts/formModeSwitcher.js]: I guess this means it works **on IE, too**? If so, you might want to spell that out.

File: osmaxx-py/osmaxx/excerptexport/static/excerptexport/stylesheets/ie-fixes.css [hunk 3]
```diff
@@ -0,0 +1,18 @@
+@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
+    /* Re-add IE default style to restyle it isable for IE uesers, as
```
Comment (das-g) [inline osmaxx-py/osmaxx/excerptexport/static/excerptexport/stylesheets/ie-fixes.css]: what is 'isable'?
