### PR TITLE
Feature/#363 fix new bbox excerpt form ms ie 11

### LINKED ISSUE #363: Fix new (BBox) excerpt form for MS IE
# To reproduce
1. click button "New excerpt'
2. select reasonably small area on map (e.g., zoom in, then click button 'Select area within current zoom')

## expected
* all 4 coordinate value form fields are filled accordingly
* size is computed

## observed
* only 'north' coordinate form field is filled
* size is displayed as 'too large' independent of bbox size

Issue created based on mail from Benjamin:

> Beim Auszug eines neuen Excerpts schreibt die Anwendung die Bounding box Begrenzung (Lat oder Long) nicht mehr automatisch heraus. Bei einer manuellen Eingabe funktioniert es einwandfrei.
Das Problem ist besteht übrigens nur im IE. Mit Firefox klappt es ebenfalls einwandfrei. Auch die Angabe wieviele % der Auszug zu gross ist wird nur im Firefox korrekt angezeigt.
Nur als kleiner Hinweis.

### PR DESCRIPTION
**Pull request by hixi**
Fixes the main issue with IE 9 - Edge not supporting the `new Event`
Also fixes two minor issues:
  - Calling the Size-Estimation-API even when one of the coordinates is null
  - setting bounds with even when one of the coordinates is null

Reviewed by:
- [x] @das-g
- [ ] @wasabideveloper

Closes #363

### CODE REVIEW

File: web_frontend/osmaxx/excerptexport/static/excerptexport/scripts/maps/new_excerpt_map.js [hunk 1]
```diff
@@ -10,14 +10,21 @@
...
+            this.inputElementsNewBoundingBox.inputElementNorth.dispatchEvent(ev);
             this.inputElementsNewBoundingBox.inputElementWest.value = locationFilterBounds._southWest.lng;
-            this.inputElementsNewBoundingBox.inputElementWest.dispatchEvent(new Event('valueUpdate'));
+            this.inputElementsNewBoundingBox.inputElementWest.dispatchEvent(ev);
             this.inputElementsNewBoundingBox.inputElementEast.value = locationFilterBounds._northEast.lng;
-            this.inputElementsNewBoundingBox.inputElementEast.dispatchEvent(new Event('valueUpdate'));
+            this.inputElementsNewBoundingBox.inputElementEast.dispatchEvent(ev);
             this.inputElementsNewBoundingBox.inputElementSouth.value = locationFilterBounds._southWest.lat;
-            this.inputElementsNewBoundingBox.inputElementSouth.dispatchEvent(new Event('valueUpdate'));
+            this.inputElementsNewBoundingBox.inputElementSouth.dispatchEvent(ev);
```
Comment (das-g) [inline web_frontend/osmaxx/excerptexport/static/excerptexport/scripts/maps/new_excerpt_map.js]: Does it make sense to send the same event (with this change it's even the same instance) 4 times?

File: web_frontend/osmaxx/excerptexport/static/excerptexport/scripts/maps/new_excerpt_map.js [hunk 2]
```diff
@@ -10,14 +10,21 @@
...
         };
+        this.areAllBoxesSet = function(){
+            return this.inputElementsNewBoundingBox.inputElementNorth.value &&
+                this.inputElementsNewBoundingBox.inputElementWest.value &&
+                this.inputElementsNewBoundingBox.inputElementEast.value &&
+                this.inputElementsNewBoundingBox.inputElementSouth.value
+        }.bind(this);
```
Comment (das-g) [inline web_frontend/osmaxx/excerptexport/static/excerptexport/scripts/maps/new_excerpt_map.js]: I kinda feel like `areAllBoxesSet()` should be a method of `this.inputElementsNewBoundingBox`, but then again, the latter has been a data-only object up to now.

File: web_frontend/osmaxx/excerptexport/static/js/ie_polyfills.js [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+        if (edge > 0) {
+            // Edge (IE 12+) => return version number
+            return parseInt(ua.substring(edge + 5, ua.indexOf('.', edge)), 10);
+        }
+
+        // other browser
+        return false;
+    }
+
+    if (detectIE()) {
```
Comment (das-g) [inline web_frontend/osmaxx/excerptexport/static/js/ie_polyfills.js]: Do we need to detect IE or could we just check whether CustomEvent is defined?

File: web_frontend/osmaxx/excerptexport/static/js/ie_polyfills.js [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+            var evt = document.createEvent( 'CustomEvent' );
+            evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );
+            return evt;
+        }
+
+        CustomEvent.prototype = window.Event.prototype;
+
+        window.CustomEvent = CustomEvent;
+    }
+})();
```
Comment (das-g) [inline web_frontend/osmaxx/excerptexport/static/js/ie_polyfills.js]: Missing newline at end of file.

File: web_frontend/osmaxx/excerptexport/static/excerptexport/scripts/maps/new_excerpt_map.js (hunk 1 above)
Comment (hixi) [inline web_frontend/osmaxx/excerptexport/static/excerptexport/scripts/maps/new_excerpt_map.js]: It was the same event before, but it might in fact be better to create a new event each time.

File: web_frontend/osmaxx/excerptexport/static/js/ie_polyfills.js (hunk 3 above)
Comment (hixi) [inline web_frontend/osmaxx/excerptexport/static/js/ie_polyfills.js]: CustomEvent _is_ defined in IE (at least in IE 11 and Edge), but doesn't allow `new` on it.

File: web_frontend/osmaxx/excerptexport/static/excerptexport/scripts/maps/new_excerpt_map.js (hunk 1 above)
Comment (das-g) [inline web_frontend/osmaxx/excerptexport/static/excerptexport/scripts/maps/new_excerpt_map.js]: wouldn't one event at the end suffice?

File: web_frontend/osmaxx/excerptexport/static/excerptexport/scripts/maps/new_excerpt_map.js (hunk 2 above)
Comment (hixi) [inline web_frontend/osmaxx/excerptexport/static/excerptexport/scripts/maps/new_excerpt_map.js]: Good idea.

**Comment by das-g** [comment]
I've added @wasabideveloper as another reviewer, because I'm not that proficient in JS.

File: web_frontend/osmaxx/excerptexport/static/excerptexport/scripts/maps/new_excerpt_map.js (hunk 1 above)
Comment (hixi) [inline web_frontend/osmaxx/excerptexport/static/excerptexport/scripts/maps/new_excerpt_map.js]: No, since you can change them individually.

Comment (wasabideveloper) [inline web_frontend/osmaxx/excerptexport/static/excerptexport/scripts/maps/new_excerpt_map.js]: Yes, BUT if we change all input elements at the same time it makes sense to fire the event only once. Because the size calculation is done EVERYTIME the event is fired! But I have no idea on which element to fire the event if we fire it only once.

File: web_frontend/osmaxx/excerptexport/static/js/ie_polyfills.js (hunk 4 above)
Comment (hixi) [inline web_frontend/osmaxx/excerptexport/static/js/ie_polyfills.js]: :white_check_mark:

File: web_frontend/osmaxx/excerptexport/static/excerptexport/scripts/maps/new_excerpt_map.js (hunk 2 above)
Comment (wasabideveloper) [inline web_frontend/osmaxx/excerptexport/static/excerptexport/scripts/maps/new_excerpt_map.js]: Enhancement proposal: 
```javascript
Object.keys(this.inputElementsNewBoundingBox).every(function(inputElementKey) {
    this.inputElementsNewBoundingBox[inputElementKey]....
}.bind(this));
```

File: web_frontend/osmaxx/excerptexport/static/excerptexport/scripts/validation/new_excerpt_validation.js [hunk 5]
```diff
@@ -18,34 +18,43 @@
             }, this);
         }.bind(this);
 
+        this.areAllBoxesSet = function(){
+            return this.bboxFields.north.value &&
+                this.bboxFields.east.value &&
+                this.bboxFields.south.value &&
+                this.bboxFields.west.value
+        }.bind(this);
```
Comment (wasabideveloper) [inline web_frontend/osmaxx/excerptexport/static/excerptexport/scripts/validation/new_excerpt_validation.js]: Same as above
```javascript
Object.keys(this.inputElementsNewBoundingBox).forEach(function(inputElementKey) {
            this.inputElementsNewBoundingBox[inputElementKey]...
}.bind(this));
```

File: web_frontend/osmaxx/excerptexport/static/js/ie_polyfills.js (hunk 3 above)
Comment (wasabideveloper) [inline web_frontend/osmaxx/excerptexport/static/js/ie_polyfills.js]: I think it's better to determine if `new` is supported instead of checking the user agent:
```javascript
try { 
    new Event('bla'); 
} catch(e) { 
    do it by yourself
}
```
